#!/bin/bash
# PDF Generation Script for JavaScript & Browser Design Patterns Documentation
# Uses pandoc with XeLaTeX for high-quality PDF output

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}  JavaScript & Browser Design Patterns PDF Generator${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

# Configuration
INPUT_FILE="master_output.md"
OUTPUT_FILE="JavaScript_Design_Patterns_Complete.pdf"
METADATA_FILE="pdf-metadata.yaml"
LOG_FILE="pdf-generation.log"

# Check if input file exists
if [ ! -f "$INPUT_FILE" ]; then
    echo -e "${RED}✗ Error: $INPUT_FILE not found${NC}"
    exit 1
fi

echo -e "${GREEN}✓ Found input file: $INPUT_FILE${NC}"

# Get file statistics
LINES=$(wc -l < "$INPUT_FILE")
WORDS=$(wc -w < "$INPUT_FILE")
SIZE=$(du -h "$INPUT_FILE" | cut -f1)

echo -e "  Lines: ${YELLOW}$LINES${NC}"
echo -e "  Words: ${YELLOW}$WORDS${NC}"
echo -e "  Size: ${YELLOW}$SIZE${NC}"
echo ""

# Create metadata file if it doesn't exist
if [ ! -f "$METADATA_FILE" ]; then
    echo -e "${YELLOW}⚙ Creating PDF metadata configuration...${NC}"
    cat > "$METADATA_FILE" << 'EOF'
---
title: "JavaScript & Browser Design Patterns"
subtitle: "Complete Reference Guide"
author: "Generated by Sonnet 4.5"
date: "November 2025"
geometry:
  - margin=1in
  - paperwidth=8.5in
  - paperheight=11in
fontsize: 11pt
linestretch: 1.15
documentclass: report
toc: true
toc-depth: 3
toc-title: "Table of Contents"
colorlinks: true
linkcolor: blue
urlcolor: blue
citecolor: green
header-includes:
  - \usepackage{fancyhdr}
  - \usepackage{graphicx}
  - \usepackage{xcolor}
  - \usepackage{listings}
  - \usepackage{fontspec}
  - \setmonofont{DejaVu Sans Mono}[Scale=0.9]
  - \usepackage[many]{tcolorbox}
  - \pagestyle{fancy}
  - \fancyhead[L]{\small JavaScript Design Patterns}
  - \fancyhead[R]{\small\thepage}
  - \fancyfoot[C]{\small Generated $(date +"%B %Y")}
  - \lstset{
      basicstyle=\ttfamily\small,
      breaklines=true,
      frame=single,
      backgroundcolor=\color{gray!10},
      numbers=left,
      numberstyle=\tiny\color{gray},
      keywordstyle=\color{blue},
      commentstyle=\color{green!50!black},
      stringstyle=\color{red},
      showstringspaces=false
    }
---
EOF
    echo -e "${GREEN}✓ Metadata file created${NC}"
fi

echo ""
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}  Starting PDF Generation${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${YELLOW}⚙ PDF Engine: XeLaTeX${NC}"
echo -e "${YELLOW}⚙ Input: $INPUT_FILE${NC}"
echo -e "${YELLOW}⚙ Output: $OUTPUT_FILE${NC}"
echo ""

# Start timer
START_TIME=$(date +%s)

# Generate PDF with pandoc
echo -e "${BLUE}► Running pandoc with XeLaTeX...${NC}"
echo ""

pandoc "$INPUT_FILE" \
  --metadata-file="$METADATA_FILE" \
  --from=markdown+smart+raw_html \
  --to=pdf \
  --pdf-engine=xelatex \
  --highlight-style=tango \
  --number-sections \
  --standalone \
  --output="$OUTPUT_FILE" \
  --verbose \
  2>&1 | tee "$LOG_FILE"

PANDOC_EXIT_CODE=$?

# End timer
END_TIME=$(date +%s)
ELAPSED=$((END_TIME - START_TIME))
MINUTES=$((ELAPSED / 60))
SECONDS=$((ELAPSED % 60))

echo ""
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"

if [ $PANDOC_EXIT_CODE -eq 0 ] && [ -f "$OUTPUT_FILE" ]; then
    PDF_SIZE=$(du -h "$OUTPUT_FILE" | cut -f1)
    echo -e "${GREEN}✓ PDF generation completed successfully!${NC}"
    echo ""
    echo -e "  Output: ${GREEN}$OUTPUT_FILE${NC}"
    echo -e "  Size: ${YELLOW}$PDF_SIZE${NC}"
    echo -e "  Time: ${YELLOW}${MINUTES}m ${SECONDS}s${NC}"
    echo ""
    echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""
    echo -e "${GREEN}✓ PDF ready: $(pwd)/$OUTPUT_FILE${NC}"
    echo ""
    
    # Ask if user wants to open the PDF
    echo -e "${YELLOW}Tip: Open with: xdg-open $OUTPUT_FILE${NC}"
    exit 0
else
    echo -e "${RED}✗ PDF generation failed${NC}"
    echo -e "  Check log file: $LOG_FILE"
    echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    exit 1
fi

